export const CAR_LIST_REQUEST = 'CAR_LIST_REQUEST'
export const CAR_LIST_SUCCESS = 'CAR_LIST_SUCCESS'
export const CAR_LIST_FAIL = 'CAR_LIST_FAIL'

export const CAR_CREATE_REQUEST = 'CAR_CREATE_REQUEST'
export const CAR_CREATE_SUCCESS = 'CAR_CREATE_SUCCESS'
export const CAR_CREATE_FAIL = 'CAR_CREATE_FAIL'
